### ISSUE TITLE
NVIDIA GeForce RTX 5080 with CUDA capability sm_120 is not compatible with the current PyTorch installation.

### ISSUE THREAD

**Issue by axalox** [bytedance/UNO#34]
Hello
Uno doesn't seem to work with rtx 5080

NVIDIA GeForce RTX 5080 with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
warnings.warn( (modifié)

**Comment by ValMystletainn** [comment]
[You https://discuss.pytorch.org/t/my-rtx5080-gpu-cant-work-with-pytorch/217301/17](https://discuss.pytorch.org/t/my-rtx5080-gpu-cant-work-with-pytorch/217301/17)

seems you need to install the pre-released pytorch to fit your GPU driver. We don't have the device with the so new driver. But I think you can try to install the pytorch metioned in this discussion. There's a good chance it'll work, since there is no special operator we used in UNO

**Comment by axalox** [comment]
Hello

It works now with the modification but it is very slow vs demo at hugging face.
Do you think an other parts needs to be upgraded ?

**Comment by ValMystletainn** [comment]
It's in expectation be slower than hf demo, since the hf zero gpu is a A100 cluster. But it's not correct if much slower.  Just a reference a 4090 with `--offload` and `fp8` is 1min per image.

I think you may use the high memory mode  and  trigger the shared memory and vmemory system in windows. so just turn on the two options and try again. If you are interested in detailed reasons,  you can read the last response by me in #19 for detailed

**Comment by axalox** [comment]
![Image](https://github.com/user-attachments/assets/dd16262e-70c3-4683-b23e-d1ca9e3035c0)

![Image](https://github.com/user-attachments/assets/7d4c9417-deaa-462f-bcea-4651ed5df6c8)

**Comment by axalox** [comment]
> It's in expectation be slower than hf demo, since the hf zero gpu is a A100 cluster. But it's not correct if much slower. Just a reference a 4090 with `--offload` and `fp8` is 1min per image.
> 
> I think you may use the high memory mode and trigger the shared memory and vmemory system in windows. so just turn on the two options and try again. If you are interested in detailed reasons, you can read the last response by me in [#19](https://github.com/bytedance/UNO/issues/19) for detailed

Oh ok
I'll try
