### ISSUE TITLE
I wonder if eval_dataloader should be wrapped by accelerator?

### ISSUE THREAD

**Issue by zerunfeng** [bytedance/UNO#49]
In train.py line 301, the eval_dataloader is wrapped by accelerator. However, it is used in the main process.

**Comment by ValMystletainn** [comment]
We wrapper the eval_dataloader, the dataset is shard in different rank. and can do distributed evaluation in different ranks. It's faster and make all the gpu work(it's important if turn to zero3 sharding and for the low gpu utililty check)

In our inner training, we do **quick evaluation** check by roughly look at the rank0 results. and do the **compelete evaluation** by gather the result to rank0 and do the log.

But for opensource released version, we use the quick evaluation check.

**Comment by zerunfeng** [comment]
> We wrapper the eval_dataloader, the dataset is shard in different rank. and can do distributed evaluation in different ranks. It's faster and make all the gpu work(it's important if turn to zero3 sharding and for the low gpu utililty check)
> 
> In our inner training, we do **quick evaluation** check by roughly look at the rank0 results. and do the **compelete evaluation ** by gather the result to rank0 and do the log.
> 
> But for opensource released version, we use the quick evaluation check.

Thanks for answering. BTW, I am training the model with my own datasets. I find the GPU memory is increasing during training. Is it normal ?

**Comment by buaawangyu** [comment]
这个问题解决了么？我也是训练到一千多步就显存不够了，80G*8，batchsize=1

**Comment by buaawangyu** [comment]
try delete:

dataloader =itertools.cycle(dataloader)
...
batch =next(dataloader)

instead using:

for step ,batch in enumerate(dataloader):
...

**Comment by buaawangyu** [comment]
https://github.com/pytorch/pytorch/issues/23900

it seems to be a  known problem of pytorch

**Comment by zerunfeng** [comment]
> [pytorch/pytorch#23900](https://github.com/pytorch/pytorch/issues/23900)
> 
> it seems to be a known problem of pytorch

Great observation! After I change the way of loading data as you provided, the GPU ussage is stable. I'm trying to make a infinite sampler for multi-gpu env.

**Comment by zerunfeng** [comment]
> [pytorch/pytorch#23900](https://github.com/pytorch/pytorch/issues/23900)
> 
> it seems to be a known problem of pytorch

Great observation! After I change the way of loading data as you provided, the GPU ussage is stable. I'm trying to make a infinite sampler for multi-gpu env.
